name: Build and publish to GitHub Container Registry

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      cache: true
      cache-mode: max
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=edge,branch=main
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}},enable=${{ !contains(github.ref, '-') }}
        type=semver,pattern={{major}},enable=${{ !contains(github.ref, '-') }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
